version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Opcional para desarrollo, así puedes ver los cambios de código
    restart: always
