apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: projects-api:latest # Puedes usar tu imagen local o subirla a Docker Hub
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-service # Ojo: coincide con el service de Redis
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP # Puedes cambiar a NodePort si necesitas acceso externo
